// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gruioififeukeqmlwuup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydWlvaWZpZmV1a2VxbWx3dXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTQ5MTcsImV4cCI6MjA3MjY3MDkxN30.qqXXHj2XBkJRzIcBtABJ1lwpC8LtT9LhFRXx_e-ABCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});